small changes :trollface:
tp-project-2024/server pull request #4
Opened 2024-01-23 13:15 UTC by jacekpoz

this PR:
- changes various names and small syntax issues that bugged me
- reworks game related tables, hopefully making them cleaner to use in the future
- fixed a few issues we discussed prior (fixing/adding IDs to tables)
- completely removes user avatars

TODO:
- [ ] fix the tests

2024-01-23 13:19 UTC, wilcorg approved these changes

2024-01-23 13:21 UTC, wilcorg approved these changes

2024-01-23 13:22 UTC, wilcorg approved these changes

2024-01-23 13:23 UTC, wilcorg approved these changes

2024-01-23 13:25 UTC, wilcorg approved these changes

2024-01-23 19:33 UTC, wilcorg requested changes
This code doesn't startup: foriegn key can't be a primary key in table
https://stackoverflow.com/questions/10982992/is-it-fine-to-have-foreign-key-as-primary-key

Possible solution:
![image](https://github.com/tp-project-2024/server/assets/40640437/0b710445-02c1-4fc5-b030-d9c63fbd6b43)

2024-01-24 00:57 UTC, jacekpoz commented
we discussed these changes on signal but do look through them once more just to make sure you're fine with all this

tests now work and should be ready to merge!

2024-01-24 19:37 UTC, wilcorg approved these changes

2024-01-24 19:37 UTC, wilcorg commented on src/main/java/org/gogame/server/domain/entities/GameJournalEntity.java
> -    @OneToOne
Is it possible to remain FK anno herę?

2024-01-24 19:43 UTC, merged